# Generated by Django 5.0.7 on 2024-07-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharRoom',
            new_name='ChatRoom',
        ),
    ]
